Document: pthread-embedded
Title: Debian pthread-embedded Manual
Author: <insert document author here>
Abstract: This manual describes what pthread-embedded is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pthread-embedded/pthread-embedded.sgml.gz

Format: postscript
Files: /usr/share/doc/pthread-embedded/pthread-embedded.ps.gz

Format: text
Files: /usr/share/doc/pthread-embedded/pthread-embedded.text.gz

Format: HTML
Index: /usr/share/doc/pthread-embedded/html/index.html
Files: /usr/share/doc/pthread-embedded/html/*.html
