Document: pthread-embeded
Title: Debian pthread-embeded Manual
Author: <insert document author here>
Abstract: This manual describes what pthread-embeded is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pthread-embeded/pthread-embeded.sgml.gz

Format: postscript
Files: /usr/share/doc/pthread-embeded/pthread-embeded.ps.gz

Format: text
Files: /usr/share/doc/pthread-embeded/pthread-embeded.text.gz

Format: HTML
Index: /usr/share/doc/pthread-embeded/html/index.html
Files: /usr/share/doc/pthread-embeded/html/*.html
